project:
  type: website
  output-dir: docs
  
website:
  title: "Home page for Daniel T. Kaplan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: CV.qmd
        text: CV
      - href: Rpackages.qmd
        text: R/CRAN packages

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



